In [3]:
import numpy as np
import matplotlib.pyplot as plt

In [40]:
X = np.array([[1,2,3,4,5,6,7,9,9,10], [100.14, 130.22, 150, 210, 230.10, 280, 260, 320, 350, 400]])

In [41]:
X

array([[  1.  ,   2.  ,   3.  ,   4.  ,   5.  ,   6.  ,   7.  ,   9.  ,
          9.  ,  10.  ],
       [100.14, 130.22, 150.  , 210.  , 230.1 , 280.  , 260.  , 320.  ,
        350.  , 400.  ]])

In [42]:
type(X)

numpy.ndarray

In [43]:
X.ndim

2

In [44]:
X.shape

(2L, 10L)

In [72]:
X[1].dtype

dtype('float64')

In [50]:
X[0].itemsize

8

In [70]:
X.data

<read-write buffer for 0x000000000A2BFE40, size 160, offset 0 at 0x0000000008506500>

In [29]:
X[0]

array([ 1,  2,  3,  4,  5,  6,  7,  9,  9, 10])

In [30]:
type(X[0])

numpy.ndarray

In [36]:
X[0].ndim

1

In [9]:
X[1]

array([100, 130, 150, 210, 230, 280, 260, 320, 350, 400])

In [12]:
X[0][5]

6

In [13]:
X[1][3]

210

In [15]:
mat1 = np.matrix(X)

In [16]:
mat1

matrix([[  1,   2,   3,   4,   5,   6,   7,   9,   9,  10],
        [100, 130, 150, 210, 230, 280, 260, 320, 350, 400]])

In [31]:
type(mat1)

numpy.matrixlib.defmatrix.matrix

In [54]:
a = np.arange(15).reshape(3,5)

In [55]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [57]:
type(a)

2

In [74]:
a1 = np.arange(10, 100, 5)
a1

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [60]:
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [67]:
c = np.zeros((4,3,5))
c

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [68]:
c.ndim

3

In [69]:
c.shape

(4L, 3L, 5L)

In [73]:
c.size

60

In [17]:
from sklearn.tree import DecisionTreeRegressor

In [18]:
regressor = DecisionTreeRegressor()

In [24]:
X_feature = X[0].reshape(-1,1)

In [25]:
regressor.fit(X_feature, X[1])

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [28]:
regressor.predict(5.5)

array([230.])