<a href="https://colab.research.google.com/github/ayaz-ncr/100ml/blob/master/09_latent_sematic_analysis_SVD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from sklearn.decomposition import TruncatedSVD
import numpy as np

In [0]:
X = np.array([[1,1,0,0,0,0], [0,1,1,0,0,0], [0,1,0,0,0,0], [0,0,0,1,0,1], [0,0,0,0,1,1]])

In [5]:
X

array([[1, 1, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 1, 1]])

In [28]:
type(X)

numpy.ndarray

In [10]:
svd = TruncatedSVD(n_components=5)
svd.fit(X)

TruncatedSVD(algorithm='randomized', n_components=5, n_iter=5,
       random_state=None, tol=0.0)

In [15]:
U = svd.fit_transform(X)
U

array([[ 1.21313142e+00, -0.00000000e+00, -0.00000000e+00,
        -7.07106781e-01, -1.68262187e-01],
       [ 1.21313142e+00,  7.38094482e-16, -3.86886736e-16,
         7.07106781e-01, -1.68262187e-01],
       [ 8.88073834e-01, -1.02653888e-15,  6.08931341e-16,
         2.22044605e-16,  4.59700843e-01],
       [-4.38811111e-17,  1.22474487e+00,  7.07106781e-01,
        -1.96261557e-17, -6.14845318e-19],
       [ 5.71383358e-17,  1.22474487e+00, -7.07106781e-01,
        -4.06512892e-16,  4.87323707e-16]])

In [16]:
sigma = svd.singular_values_
sigma

array([1.93185165, 1.73205081, 1.        , 1.        , 0.51763809])

In [18]:
VT1 = svd.components_
VT

array([[ 3.25057584e-01,  8.88073834e-01,  3.25057584e-01,
        -1.04696993e-16,  8.46742160e-17, -6.32138733e-18],
       [ 7.88679970e-16, -7.22769792e-16,  1.53506881e-15,
         4.08248290e-01,  4.08248290e-01,  8.16496581e-01],
       [-6.51779658e-16,  6.88300111e-16, -1.14541144e-15,
         7.07106781e-01, -7.07106781e-01,  1.90604132e-16],
       [-7.07106781e-01,  4.14759827e-16,  7.07106781e-01,
         1.11425524e-16, -7.29453865e-16, -4.07187238e-16],
       [-6.27963030e-01,  4.59700843e-01, -6.27963030e-01,
        -3.58264727e-16,  1.67013603e-15,  1.31890051e-15]])

In [11]:
svd.explained_variance_

array([0.30701706, 0.36      , 0.2       , 0.2       , 0.05298294])

In [12]:
svd.explained_variance_ratio_

array([0.27412237, 0.32142857, 0.17857143, 0.17857143, 0.0473062 ])

TruncatedSVD is basically a wrapper around sklearn.utils.extmath.randomized_svd

In [20]:
from sklearn.utils.extmath import randomized_svd

U_, Sigma_, VT_ = randomized_svd(X, 
                              n_components=6,
                              n_iter=5,
                              random_state=None)
U_

array([[ 6.27963030e-01, -0.00000000e+00,  0.00000000e+00,
        -7.07106781e-01, -3.25057584e-01],
       [ 6.27963030e-01,  3.79891848e-16, -2.62134913e-16,
         7.07106781e-01, -3.25057584e-01],
       [ 4.59700843e-01, -2.27236182e-16,  2.76012701e-16,
        -1.11022302e-16,  8.88073834e-01],
       [-1.21498718e-16,  7.07106781e-01, -7.07106781e-01,
        -3.21013380e-16,  4.63591815e-16],
       [-6.81436036e-17,  7.07106781e-01,  7.07106781e-01,
        -5.88784672e-17, -3.56336983e-18]])

In [21]:
sigma_

array([1.93185165, 1.73205081, 1.        , 1.        , 0.51763809])

In [0]:
VT_

Using the scipy library

In [0]:
from scipy.sparse.linalg import svds
from scipy import sparse

In [0]:
s_X2 = sparse.csr_matrix(X)
s_X2 = s_X2.asfptype()
num_components = 4
U2, sigma2, VT2 = svds(s_X2, k=num_components)

In [47]:
U2

array([[ 6.43601479e-01, -2.92877340e-01, -5.55111512e-17,
         6.27963030e-01],
       [-6.43601479e-01,  2.92877340e-01, -5.55111512e-17,
         6.27963030e-01],
       [ 1.11022302e-16,  0.00000000e+00,  2.22044605e-16,
         4.59700843e-01],
       [ 2.92877340e-01,  6.43601479e-01,  7.07106781e-01,
        -2.08624151e-16],
       [-2.92877340e-01, -6.43601479e-01,  7.07106781e-01,
         1.03463589e-16]])

In [48]:
sigma2

array([1.        , 1.        , 1.73205081, 1.93185165])

In [49]:
VT2

array([[ 6.43601479e-01, -1.11022302e-16, -6.43601479e-01,
         2.92877340e-01, -2.92877340e-01,  2.77555756e-16],
       [-2.92877340e-01,  5.55111512e-17,  2.92877340e-01,
         6.43601479e-01, -6.43601479e-01,  1.11022302e-16],
       [-3.20493781e-17,  6.40987562e-17, -3.20493781e-17,
         4.08248290e-01,  4.08248290e-01,  8.16496581e-01],
       [ 3.25057584e-01,  8.88073834e-01,  3.25057584e-01,
        -1.07991807e-16,  5.35566944e-17, -5.44351128e-17]])

In [31]:
type(np.random.random((3,3)))

numpy.ndarray